config/routes.rb
Rails.application.routes.draw do
  post "sessions/new", to: "sessions#new"
  post "admin/sessions/new", to: "sessions#admin_new"
  get "login", to: "sessions#login"
  get "admin/login", to: "sessions#admin_login"
  delete "session", to: "sessions#destroy"
  post "tasks/search", to: "tasks#search"
  get "tasks/search", to: "tasks#index"
  get "tasks/order/:type", to: "tasks#index"
  resources :tasks
  namespace :admin, path: "1o2rf1n2o321" do
    resources :users
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "tasks#index"
end

app/models/task.rb
class Task < ApplicationRecord
  enum state: { pending: 0, processing: 1, finished: 2 }
  enum piority: { high: 0, medium: 1, low: 2 }
  validates :title, presence: true
  validate :valid_date
  belongs_to :user
  has_and_belongs_to_many :tags

  def valid_date
    if start_time >= end_time
      errors.add :start_time, "#{I18n.t("error_date")}"
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :login?

  def login?
    @current_user = User.find_by id: session[:current_user_id]
    redirect_to login_path unless @current_user
  end

  def search
    puts params[:tag]
    @tasks = @current_user.tasks.where("title = ?", params[:title]).includes(:user).page(params[:page]) if params[:title]
    @tasks = @current_user.tasks.where("state = ?", Task.states[params[:state]]).includes(:user).page(params[:page]) if params[:state]
    @tasks = Tag.find_by(name: params[:tag]).tasks.where(user: @current_user).includes(:user).page(params[:page]) if Tag.find_by(name: params[:tag])
    @tasks ||= Task.where(title: nil).includes(:user).page(params[:page])
    render :index
  end

  # GET /tasks
  # GET /tasks.json
  def index
    case params[:type]
    when "end_time"
      @tasks = @current_user.tasks.order("end_time").includes(:user).page(params[:page])
    when "piority"
      @tasks = @current_user.tasks.order("piority").includes(:user).page(params[:page])
    else
      @tasks = @current_user.tasks.order("created_at").includes(:user).page(params[:page])
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    params[:task][:tag].split(" ").each do |tag|
      unless tag == ""
        @task.tags << (Tag.find_by(name: tag) || Tag.create(name: tag))
      end
    end
    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: I18n.t("c_task_happy") }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        @task.tags.destroy_all
        params[:task][:tag].split(" ").each do |tag|
          unless tag == ""
            @task.tags << (Tag.find_by(name: tag) || Tag.create(name: tag))
          end
        end
        format.html { redirect_to @task, notice: I18n.t("u_task_happy") }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { unless @current_user.admin then redirect_to tasks_url, notice: I18n.t("d_task_happy") else redirect_to admin_users_path, notice: I18n.t("d_task_happy") end }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_task
    @task = Task.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def task_params
    task = Task.find_by(id: params[:id])
    params[:task][:user_id] = task.user if task
    params[:task][:user_id] ||= @current_user.id
    params.require(:task).permit(:name, :title, :content, :user_id, :start_time, :end_time, :piority, :state)
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_with(model: task) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= "#{I18n.t(error.attribute)}：#{error.message}" %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label "#{I18n.t("title")}" %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label "#{I18n.t("content")}" %>
    <%= form.text_field :content %>
  </div>

  <div class="field">
    <%= form.label "#{I18n.t("tag")}" %>
    <% tags = "" %>
    <% @task.tags.select { |tag| tags += "#{tag.name} " } %>
    <%= form.text_field :tag, value: tags, placeholder: "多個標籤使用空格分開" %>
  </div>
  
  <div class="field">
    <%= form.label "#{I18n.t("start_time")}" %>
    <%= form.datetime_select :start_time %>
  </div>

  <div class="field">
    <%= form.label "#{I18n.t("end_time")}" %>
    <%= form.datetime_select :end_time %>
  </div>

  <div class="field">
    <%= form.label "#{I18n.t("piority")}" %>
    <%= form.select(:piority, { "#{I18n.t("low")}": "low", "#{I18n.t("medium")}": "medium", "#{I18n.t("high")}": "high" }) %>
  </div>

  <div class="field">
    <%= form.label "#{I18n.t("state")}" %>
    <%= form.select(:state, { "#{I18n.t("pending")}": "pending", "#{I18n.t("processing")}": "processing", "#{I18n.t("finished")}": "finished" }) %>
  </div>

  <div class="actions">
    <%= form.submit "#{I18n.t("create_task")}" %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1><%= I18n.t("edit_task") %></h1>

<%= render "form", task: @task %>

<%= link_to I18n.t("show"), @task %> |
<% unless @current_user.admin %>
<%= link_to I18n.t("back"), tasks_path %>
<% else %>
<%= link_to I18n.t("back"), admin_users_path %>
<% end %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= I18n.t("tasks") %></h1>
<%= form_tag "/tasks/search" do %>
  <%= text_field_tag "title", nil, placeholder: "標題", class: "tbx_normal" %>
  <%= submit_tag "查詢", class: "btn btn-secondary" %>
<% end %>

<%= form_tag "/tasks/search" do %>
  <%= text_field_tag "tag", nil, placeholder: "標籤", class: "tbx_normal" %>
  <%= submit_tag "查詢", class: "btn btn-secondary" %>
<% end %>

<%= form_tag "/tasks/search" do %>
  <select name="state", class: class="btn btn-info dropdown-toggle" >
  <option value="pending"><%= I18n.t("pending") %></option>
  <option value="processing"><%= I18n.t("processing") %></option>
  <option value="finished"><%= I18n.t("finished") %></option>
</select>
  <%= submit_tag "查詢", class: "btn btn-secondary" %>
<% end %>
<table class="table">
  <thead>
    <tr>
      <th><%= I18n.t("title") %></th>
      <th><%= I18n.t("content") %></th>
      <th><%= I18n.t("tag") %></th>
      <th><%= I18n.t("start_time") %></th>
      <th><%= I18n.t("end_time") %></th>
      <th><%= I18n.t("piority") %></th>
      <th><%= I18n.t("state") %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.content %></td>
        <td>
        <% task.tags.each do |tag| %>
          <%= "#{tag.name}/" %>
          <% end %>
        </td>
        <td><%= task.start_time %></td>
        <td><%= task.end_time %></td>
        <td><%= I18n.t(task.piority) %></td>
        <td><%= I18n.t(task.state) %></td>
        <td><%= link_to I18n.t("show"), task, class: "btn btn-success" %></td>
        <td><%= link_to I18n.t("edit"), edit_task_path(task), class: "btn btn-info" %></td>
        <td><%= link_to I18n.t("destroy"), task, method: :delete, id: "delete", data: { confirm: I18n.t("confirm") }, class: "btn btn-danger btn-xs" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @tasks %>
<br>

<%= link_to I18n.t("create_task"), new_task_path, class: "breadcrumb-item" %>
<%= link_to I18n.t("order_by_end_time"), "/tasks/order/end_time" %>
<%= link_to I18n.t("order_by_piority"), "/tasks/order/piority" %></br>
<%= link_to "登出", session_path, method: :delete %>

app/views/tasks/new.html.erb
<h1><%= I18n.t("new_task") %></h1>

<%= render "form", task: @task %>

<% unless @current_user.admin %>
<%= link_to I18n.t("back"), tasks_path %>
<% else %>
<%= link_to I18n.t("back"), admin_users_path %>
<% end %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= "#{I18n.t("title")}: " %></strong>
  <%= @task.title %>
</p>

<p>
  <strong><%= "#{I18n.t("content")}: " %></strong>
  <%= @task.content %>
</p>

<p>
  <strong><%= "#{I18n.t("tag")}: " %></strong>
  <% @task.tags.each do |tag| %>
  <%= "#{tag.name}/" %>
  <% end %>
</p>

<p>
  <strong><%= "#{I18n.t("start_time")}: " %></strong>
  <%= @task.start_time %>
</p>

<p>
  <strong><%= "#{I18n.t("end_time")}: " %></strong>
  <%= @task.end_time %>
</p>

<p>
  <strong><%= "#{I18n.t("piority")}: " %></strong>
  <%= I18n.t("#{@task.piority}") %>
</p>

<p>
  <strong><%= "#{I18n.t("state")}: " %></strong>
  <%= I18n.t("#{@task.state}") %>
</p>

<%= link_to I18n.t("edit"), edit_task_path(@task) %> |
<% unless @current_user.admin %>
<%= link_to I18n.t("back"), tasks_path %>
<% else %>
<%= link_to I18n.t("back"), admin_users_path %>
<% end %>