config/routes.rb
Rails.application.routes.draw do
  post "sessions/new", to: "sessions#new"
  post "admin/sessions/new", to: "sessions#admin_new"
  get "login", to: "sessions#login"
  get "admin/login", to: "sessions#admin_login"
  delete "session", to: "sessions#destroy"
  post "tasks/search", to: "tasks#search"
  get "tasks/search", to: "tasks#index"
  get "tasks/order/:type", to: "tasks#index"
  resources :tasks
  namespace :admin, path: "1o2rf1n2o321" do
    resources :users
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "tasks#index"
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks
  before_destroy :destroy_tasks
  before_destroy :have_other_admin_to_destroy
  validates :name , presence: true
  validates :email, presence: true
  validates :phone, presence: true
  validates :password, presence: true
  def destroy_tasks
    tasks = Task.where user_id: id
    tasks.each do |task|
        task.destroy
    end
  end

  def have_other_admin_to_destroy
    if admin
        unless User.where(admin: true).count > 1
            errors.add :user, "管理員僅剩餘1名，故無法刪除"
            throw(:abort)
        end
    end
  end
  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :login?

  def login?
    @current_user = User.find_by id: session[:current_user_id]
    redirect_to admin_login_path unless @current_user
  end

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @tasks = @user.tasks.page(params[:page])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to admin_users_path(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to admin_users_path(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    @notice = @user.errors[:user] || "User was successfully destroy."
    puts @user.errors[:user]
    respond_to do |format|
      format.html { redirect_to admin_users_url, notice: @user.errors[:user].to_s || "User was successfully destroy." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name, :phone, :email, :admin, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :phone, :email)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_with(model: [:admin, user]) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="field">
  <%= form.label :admin %>
  <%= form.check_box :admin %>
</div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<h1>Editing User</h1>

<%= render "form", user: @user %>
<% puts "user:#{@user.name}" %>
<%= link_to "Show", admin_users_path(@user) %> |
<%= link_to "Back", admin_users_path %>

app/views/admin/users/index.html.erb
<p id="notice"><%=  notice   %></p>
<h1>Users</h1>
<table class = "table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Email</th>
      <th>task count</th>
      <th>authority</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.phone %></td>
        <td><%= user.email %></td>
        <td><%= user.tasks.count %></td>
        <td><%= if user.admin then "admin" else "normal" end %></td>
        <td><%= link_to 'Show', admin_user_path(user) %></td>
        <td><%= link_to 'Edit', edit_admin_user_path(user) %></td>
        <td><%= link_to 'Destroy', admin_user_url(user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_admin_user_path %>
<%= link_to '登出', session_path, method: :delete %>

app/views/admin/users/new.html.erb
<h1>New User</h1>

<%= render "form", user: @user %>

<%= link_to "Back", admin_users_path %>

app/views/admin/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @user.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<table class="table">
  <thead>
    <tr>
      <th><%= I18n.t("title") %></th>
      <th><%= I18n.t("content") %></th>
      <th><%= I18n.t("tag") %></th>
      <th><%= I18n.t("start_time") %></th>
      <th><%= I18n.t("end_time") %></th>
      <th><%= I18n.t("piority") %></th>
      <th><%= I18n.t("state") %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.content %></td>
        <td>
        <% task.tags.each do |tag| %>
          <%= "#{tag.name}/" %>
          <% end %>
        </td>
        <td><%= task.start_time %></td>
        <td><%= task.end_time %></td>
        <td><%= I18n.t(task.piority) %></td>
        <td><%= I18n.t(task.state) %></td>
        <td><%= link_to I18n.t("show"), task, class: "btn btn-success" %></td>
        <td><%= link_to I18n.t("edit"), edit_task_path(task), class: "btn btn-info" %></td>
        <td><%= link_to I18n.t("destroy"), task, method: :delete, id: "delete", data: { confirm: I18n.t("confirm") }, class: "btn btn-danger btn-xs" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @tasks %>
<%= link_to "Edit", edit_admin_user_path(@user) %> |
<%= link_to "Back", admin_users_path %>